project:
  type: website

website:
  title: "Advent of code - 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis/day_1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



